# Font
font_family      JetBrainsMono Nerd Font
font_size        12.0

# Run fastfetch on kitty open
startup_session  none
shell_integration enabled

# Launch fastfetch when kitty starts
launch_action    fastfetch
